# Generated by Django 5.2.4 on 2025-08-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_newslettercampaign_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_demo_url',
            field=models.URLField(blank=True, help_text='Live demo/deployment URL', null=True),
        ),
    ]
