# Generated by Django 5.2.4 on 2025-08-10 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_live_demo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_content', models.TextField(blank=True, help_text='Raw repository content from Gitingest')),
                ('embeddings_data', models.TextField(blank=True, help_text='JSON serialized embeddings and chunks')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rag_data', to='portfolio.project')),
            ],
        ),
    ]
