# Generated by Django 5.2.4 on 2025-08-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_projectrag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='sent_to_newsletter',
            field=models.BooleanField(default=False, help_text='Has this blog post been sent to newsletter subscribers?'),
        ),
    ]
