# Generated by Django 5.2.4 on 2025-08-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_blogpost_sent_to_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrag',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching Repository'), ('chunking', 'Processing Content'), ('embedding', 'Creating Embeddings'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='projectrag',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Processing progress (0-100)'),
        ),
    ]
